### ISSUE TITLE
[Serious Issue] Serious Issue

### ISSUE THREAD

**Issue by Rektorn** [SimonAlling/kurve#1]
Hit detection does not work properly. A worm cannot collide with itself.

**Comment by SimonAlling** [comment]
It does now. Although it sometimes happens that a Kurve suddenly dies for no reason, "crashing into itself". The bug is not reproducible AFAIK, but it has only ever happened on a Kurve that I actually play; never on uncontrolled ones.

**Comment by SimonAlling** [comment]
Previously mentioned random death bug is solved and collision detection is completely rewritten anyway.
